name: Integration tests

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          path: swedbank-pay-woocommerce-checkout

      - name: WooCommerce Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          repository: woocommerce/woocommerce
          ref: 5.9.0
          path: woocommerce

      - name: Install dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          extension: intl, mbstring, json, bcmath
          coverage: xdebug
          tools: composer, php-cs-fixer, phpunit:7.5.20, phpcpd, phpmd

      - name: Set up MySQL
        run: sudo systemctl start mysql.service

      - name: Set up node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: '12'

      - name: Run PHPCS inspection
        run: |
          composer global require "wp-coding-standards/wpcs"
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs
          cd $GITHUB_WORKSPACE/swedbank-pay-woocommerce-checkout
          phpcs --standard=WordPress-Core --report=code --ignore=woocommerce,vendors,tests,docs,build,.github,assets/js/*.min.js --runtime-set ignore_warnings_on_exit true ./

      - name: Upload artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          path: |
            /tmp/wordpress/wp-content/uploads/wc-logs/*.log
            /tmp/swedbank-pay-woocommerce-checkout.zip

      - name: Upload code coverage report to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
